"""A small line protocol for local models, compiled by the marked-plan parser.

The model only extracts facts and repeat nesting. Dates, units, targets and
roles remain explicit; Garmin YAML fields and repeat offsets are generated by
the application. This is an opt-in experiment until a paired golden run passes.
"""

from __future__ import annotations

import re
from typing import Any

import yaml

from ..marked_plan import compile_marked_text

_ROLES = {
    "warmup": "разминка",
    "active": "работа",
    "recovery": "восстановление",
    "cooldown": "заминка",
}
_MEASURE = re.compile(r"^(?P<number>\d+(?:[.,]\d+)?)\s*(?P<unit>km|m|min|s)$", re.IGNORECASE)
_RANGE = re.compile(r"^\d{2,3}-\d{2,3}$")
_PACE = re.compile(r"^\d{1,2}:\d{2}(?:-\d{1,2}:\d{2})?$")


class CompactFormatError(ValueError):
    """A model response does not conform to the line protocol."""


def _valid_pace_target(value: str) -> bool:
    return bool(_PACE.fullmatch(value)) and all(
        int(part.split(":")[0]) >= 1 and int(part.split(":")[1]) < 60
        for part in value.split("-")
    )


def compact_to_yaml(
    response: str, *, hr_zones: dict[str, Any] | None = None
) -> tuple[str, list[str]]:
    """Compile strict ``W/S/R/E`` lines into validated Garmin YAML."""
    marked: list[str] = []
    repeat_depth = 0
    workouts = 0
    for line_number, original in enumerate(response.splitlines(), 1):
        line = original.strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split("|")]
        tag = parts[0]
        if tag == "W":
            if repeat_depth:
                raise CompactFormatError(f"line {line_number}: repeat is not closed before W")
            if len(parts) != 3 or not parts[2]:
                raise CompactFormatError(f"line {line_number}: expected W|date-or--|title")
            when = parts[1] if parts[1] != "-" else "без даты"
            marked.extend([f"==== ТРЕНИРОВКА ==== {when} — {parts[2]}", ""])
            workouts += 1
        elif tag == "S":
            if not workouts or len(parts) != 4 or parts[1] not in _ROLES:
                raise CompactFormatError(f"line {line_number}: expected S|role|measure|target")
            marked.extend(["**** ШАГ ****", f"Тип: {_ROLES[parts[1]]}"])
            measure = parts[2]
            if measure != "-":
                match = _MEASURE.fullmatch(measure)
                if not match:
                    raise CompactFormatError(f"line {line_number}: invalid measure {measure!r}")
                unit = match.group("unit").lower()
                label = "Дистанция" if unit in {"km", "m"} else "Длительность"
                native_unit = {"km": "км", "m": "м", "min": "мин", "s": "сек"}[unit]
                marked.append(f"{label}: {match.group('number')} {native_unit}")
            target = parts[3]
            if target != "-":
                try:
                    kind, value = target.split(":", 1)
                except ValueError as exc:
                    raise CompactFormatError(f"line {line_number}: invalid target {target!r}") from exc
                if kind == "hr" and (_RANGE.fullmatch(value) or re.fullmatch(r"(?:Z[1-5]|до\s*\d{2,3})", value)):
                    marked.append(f"Пульс: {value}")
                elif kind == "pace" and _valid_pace_target(value):
                    marked.append(f"Темп: {value}")
                elif kind == "cad" and _RANGE.fullmatch(value):
                    marked.append(f"Частота шагов: {value}")
                else:
                    raise CompactFormatError(f"line {line_number}: invalid target {target!r}")
            marked.append("")
        elif tag == "R":
            if not workouts or len(parts) != 2 or not parts[1].isdigit() or int(parts[1]) < 2:
                raise CompactFormatError(f"line {line_number}: expected R|count (count >= 2)")
            repeat_depth += 1
            marked.append(f"**** ПОВТОР: {parts[1]} РАЗ ****")
        elif tag == "E":
            if len(parts) != 1 or not repeat_depth:
                raise CompactFormatError(f"line {line_number}: E without open repeat")
            repeat_depth -= 1
            marked.append("**** КОНЕЦ ПОВТОРА ****")
        elif tag == "B":
            if not workouts or len(parts) != 2:
                raise CompactFormatError(f"line {line_number}: expected B|name:seconds:reps;...")
            drills: list[str] = []
            for chunk in parts[1].split(";"):
                fields = [field.strip() for field in chunk.rsplit(":", 2)]
                if len(fields) != 3 or not fields[0] or not fields[1].isdigit() or not fields[2].isdigit():
                    raise CompactFormatError(f"line {line_number}: invalid SBU drill {chunk!r}")
                drills.append(f"{fields[0]} — {fields[2]}×{fields[1]} сек")
            marked.extend(["**** ШАГ ****", "Тип: СБУ", "Упражнения: " + "; ".join(drills), ""])
        else:
            raise CompactFormatError(f"line {line_number}: unknown command {tag!r}")
    if not workouts or repeat_depth:
        raise CompactFormatError("response has no workout or an unclosed repeat")
    compiled = compile_marked_text("\n".join(marked), hr_zones=hr_zones)
    if compiled.data is None:
        raise CompactFormatError("; ".join(compiled.errors[:5]))
    return yaml.safe_dump(compiled.data, allow_unicode=True, sort_keys=False), compiled.warnings


COMPACT_SYSTEM_PROMPT = """Convert the user's running workouts into the line protocol below. Output lines only, no YAML, JSON, markdown or explanation.
W|DD.MM.YYYY or -|short title starts each workout. Use - if no date is stated; never invent a date.
S|role|measure|target is one step in source order. role = warmup, active, recovery, cooldown. measure = number+km/m/min/s or - if absent. target = - unless the source states a numeric goal; allowed hr:130-145, hr:до 140, hr:Z2, pace:4:50-5:00, pace:5:50, cad:175-185. Do not infer a target from subjective words.
R|count begins a repeated body; E closes it. Put R before the repeated steps, E after; nested repeats are allowed. Do not calculate Garmin offsets.
B|drill name:seconds:reps;other drill:seconds:reps is one SBU block.
Preserve every stated step, recovery and repetition. No totals or comments. Do not add facts absent from source.
Example:
W|-|Intervals
S|warmup|2km|-
R|4
S|active|800m|pace:4:20-4:30
S|recovery|400m|-
E
S|cooldown|1km|-
"""
